export const JIAZI_ZHI_MAPPING = {
  "甲子": { name: "陽平治", location: "彭州", symbol: "功曹", tan: "靈真應妙壇", jing: "通玄致真靖", official: "左都領", title: "通玄" },
  "乙丑": { name: "鹿堂治", location: "綿竹", symbol: "神君", tan: "靈應通真壇", jing: "復性登真靖", official: "左都領", title: "復性" },
  "丙寅": { name: "鶴鳴治", location: "大邑", symbol: "上仙", tan: "應妙合英壇", jing: "通真澄化靖", official: "左都領", title: "通真" },
  "丁卯": { name: "葛貴治", location: "彭州", symbol: "太上", tan: "三界集神壇", jing: "洞真自然靖", official: "左都領", title: "暢玄" },
  "戊辰": { name: "庚除治", location: "綿竹", symbol: "真君", tan: "三界混真壇", jing: "元一保真靖", official: "左都領", title: "元一" },
  "己巳": { name: "秦中治", location: "德陽", symbol: "真人", tan: "三界集真壇", jing: "澄心復真靖", official: "左都領", title: "澄心" },
  "庚午": { name: "真多治", location: "金堂", symbol: "真君", tan: "玄一守真壇", jing: "保性宏真靖", official: "左都領", title: "保性" },
  "辛未": { name: "昌利治", location: "金堂", symbol: "仙人", tan: "玄妙通真壇", jing: "登真明性靖", official: "左都領", title: "登真" },
  "壬申": { name: "隸上治", location: "廣漢", symbol: "神仙", tan: "通玄會真壇", jing: "混合明真靖", official: "右都領", title: "混合" },
  "癸酉": { name: "湧泉治", location: "德陽", symbol: "大神", tan: "玄妙應真壇", jing: "清虛自然靖", official: "右都領", title: "清虛" },
  "甲戌": { name: "稠粳治", location: "新都", symbol: "神君", tan: "雷霆應化壇", jing: "致真通玄靖", official: "右都領", title: "致真" },
  "乙亥": { name: "北平治", location: "什邡", symbol: "上人", tan: "玉堂贊化壇", jing: "降真集靈靖", official: "右都領", title: "降真" },
  "丙子": { name: "本竹治", location: "什邡", symbol: "仙人", tan: "飛捷報應壇", jing: "混元至真靖", official: "右都領", title: "至真" },
  "丁丑": { name: "蒙秦治", location: "什邡", symbol: "真人", tan: "守玄靜一壇", jing: "虛一通真靖", official: "右都領", title: "虛一" },
  "戊寅": { name: "平蓋治", location: "新津", symbol: "仙人", tan: "玄真通妙壇", jing: "集真洞化靖", official: "右都領", title: "集真" },
  "己卯": { name: "雲台治", location: "蒼溪", symbol: "真人", tan: "凝神定性壇", jing: "與道合真靖", official: "右都領", title: "與道" },
  "庚辰": { name: "濜口治", location: "漢中", symbol: "仙人", tan: "英化普照壇", jing: "超元洞真靖", official: "平炁", title: "超元" },
  "辛巳": { name: "後城治", location: "金堂", symbol: "仙人", tan: "坎離合元壇", jing: "涵虛復真靖", official: "平炁", title: "涵虛" },
  "壬午": { name: "公慕治", location: "什邡", symbol: "真人", tan: "合妙混元壇", jing: "自然成真靖", official: "平炁", title: "成真" },
  "癸未": { name: "平剛治", location: "都江堰", symbol: "上仙", tan: "百神集應壇", jing: "元照虛真靖", official: "平炁", title: "元照" },
  "甲申": { name: "主簿治", location: "蒲江", symbol: "大神", tan: "神妙通玄壇", jing: "清真正性靖", official: "平炁", title: "清正" },
  "乙酉": { name: "玉堂治", location: "都江堰", symbol: "真人", tan: "三界混元壇", jing: "澄性成真靖", official: "平炁", title: "澄性" },
  "丙戌": { name: "北鐸治", location: "都江堰", symbol: "神君", tan: "靈一守玄壇", jing: "保真湛然靖", official: "平炁", title: "保真" },
  "丁亥": { name: "安都治", location: "彭州", symbol: "仙人", tan: "正一玄妙壇", jing: "虛白通真靖", official: "平炁", title: "虛白" },
  "戊子": { name: "陽平治", location: "彭州", symbol: "功曹", tan: "三臺保護壇", jing: "自然合真靖", official: "左都領", title: "自然" },
  "己丑": { name: "鹿堂治", location: "綿竹", symbol: "神君", tan: "道一守玄壇", jing: "虛一守真靖", official: "左都領", title: "虛一" },
  "庚寅": { name: "鶴鳴治", location: "大邑", symbol: "上仙", tan: "飛魔演慶壇", jing: "湛真宏化靖", official: "左都領", title: "湛真" },
  "辛卯": { name: "漓沅治", location: "彭州", symbol: "仙人", tan: "觀靜清虛壇", jing: "保真會一靖", official: "左都領", title: "保真" },
  "壬辰": { name: "葛貴治", location: "彭州", symbol: "太上", tan: "璇璣應化壇", jing: "沖虛會真靖", official: "左都領", title: "沖虛" },
  "癸巳": { name: "庚除治", location: "綿竹", symbol: "真君", tan: "玉堂靜玄壇", jing: "攝真召靈靖", official: "左都領", title: "攝真" },
  "甲午": { name: "秦中治", location: "德陽", symbol: "真人", tan: "靈真應妙壇", jing: "感真集靈靖", official: "左都領", title: "感真" },
  "乙未": { name: "真多治", location: "金堂", symbol: "真君", tan: "靈應通真壇", jing: "制魔澄真靖", official: "左都領", title: "制魔" },
  "丙申": { name: "昌利治", location: "金堂", symbol: "仙人", tan: "應妙合英壇", jing: "通真會應靖", official: "右都領", title: "通真" },
  "丁酉": { name: "隸上治", location: "廣漢", symbol: "神仙", tan: "三界集神壇", jing: "飛神達真靖", official: "右都領", title: "飛神" },
  "戊戌": { name: "湧泉治", location: "德陽", symbol: "大神", tan: "三界混真壇", jing: "存真守一靖", official: "右都領", title: "存真" },
  "己亥": { name: "稠粳治", location: "新都", symbol: "神君", tan: "三界集真壇", jing: "念性守真靖", official: "右都領", title: "念性" },
  "庚子": { name: "北平治", location: "什邡", symbol: "上人", tan: "玄一守真壇", jing: "葆真混元靖", official: "右都領", title: "葆真" },
  "辛丑": { name: "本竹治", location: "什邡", symbol: "仙人", tan: "玄妙通真壇", jing: "韜光固真靖", official: "右都領", title: "韜光" },
  "壬寅": { name: "蒙秦治", location: "什邡", symbol: "真人", tan: "通玄會真壇", jing: "混然合真靖", official: "右都領", title: "混然" },
  "癸卯": { name: "平蓋治", location: "新津", symbol: "仙人", tan: "玄妙應真壇", jing: "與聖合真靖", official: "右都領", title: "與聖" },
  "甲辰": { name: "雲台治", location: "蒼溪", symbol: "真人", tan: "雷霆應化壇", jing: "致真通玄靖", official: "平炁", title: "致真" },
  "乙巳": { name: "濜口治", location: "漢中", symbol: "仙人", tan: "玉堂贊化壇", jing: "降真集靈靖", official: "平炁", title: "降真" },
  "丙午": { name: "後城治", location: "金堂", symbol: "仙人", tan: "飛捷報應壇", jing: "混元至真靖", official: "平炁", title: "混元" },
  "丁未": { name: "公慕治", location: "什邡", symbol: "真人", tan: "守玄靜一壇", jing: "虛一通真靖", official: "平炁", title: "虛一" },
  "戊申": { name: "平剛治", location: "都江堰", symbol: "上仙", tan: "玄真通妙壇", jing: "集真洞化靖", official: "平炁", title: "集真" },
  "己酉": { name: "主簿治", location: "蒲江", symbol: "大神", tan: "凝神定性壇", jing: "與道合真靖", official: "平炁", title: "與道" },
  "庚戌": { name: "玉堂治", location: "都江堰", symbol: "真人", tan: "英化普照壇", jing: "超元洞真靖", official: "平炁", title: "超元" },
  "辛亥": { name: "北鐸治", location: "都江堰", symbol: "神君", tan: "坎離合元壇", jing: "涵虛復真靖", official: "平炁", title: "涵虛" },
  "壬子": { name: "安都治", location: "彭州", symbol: "仙人", tan: "合妙混元壇", jing: "自然成真靖", official: "左都領", title: "自然" },
  "癸丑": { name: "陽平治", location: "彭州", symbol: "功曹", tan: "百神集應壇", jing: "元照虛真靖", official: "左都領", title: "元照" },
  "甲寅": { name: "鹿堂治", location: "綿竹", symbol: "神君", tan: "神妙通玄壇", jing: "清真正性靖", official: "左都領", title: "清正" },
  "乙卯": { name: "鶴鳴治", location: "大邑", symbol: "上仙", tan: "三界混元壇", jing: "澄性成真靖", official: "左都領", title: "澄性" },
  "丙辰": { name: "漓沅治", location: "彭州", symbol: "仙人", tan: "靈一守玄壇", jing: "保真湛然靖", official: "左都領", title: "保真" },
  "丁巳": { name: "葛貴治", location: "彭州", symbol: "太上", tan: "正一玄妙壇", jing: "虛白通真靖", official: "左都領", title: "虛白" },
  "戊午": { name: "庚除治", location: "綿竹", symbol: "真君", tan: "三臺保護壇", jing: "自然合真靖", official: "左都領", title: "自然" },
  "己未": { name: "秦中治", location: "德陽", symbol: "真人", tan: "道一守玄壇", jing: "虛一守真靖", official: "左都領", title: "虛一" },
  "庚申": { name: "真多治", location: "金堂", symbol: "真君", tan: "飛魔演慶壇", jing: "湛真宏化靖", official: "右都領", title: "湛真" },
  "辛酉": { name: "昌利治", location: "金堂", symbol: "仙人", tan: "觀靜清虛壇", jing: "保真會一靖", official: "右都領", title: "保真" },
  "壬戌": { name: "隸上治", location: "廣漢", symbol: "神仙", tan: "璇璣應化壇", jing: "沖虛會真靖", official: "右都領", title: "沖虛" },
  "癸亥": { name: "湧泉治", location: "德陽", symbol: "大神", tan: "玉堂靜玄壇", jing: "攝真召靈靖", official: "右都領", title: "攝真" }
};
// --- 生肖對應本命北斗星君 ---
export const ZODIAC_MAPPING = {
  '子': { star: '貪狼星', roleType: 'judge', note: '北斗第一陽明貪狼星君 (鼠)' }, 
  '丑': { star: '巨門星', roleType: 'admin', note: '北斗第二陰精巨門星君 (牛)' },
  '亥': { star: '巨門星', roleType: 'admin', note: '北斗第二陰精巨門星君 (豬)' },
  '寅': { star: '祿存星', roleType: 'admin', note: '北斗第三真人祿存星君 (虎)' },
  '戌': { star: '祿存星', roleType: 'admin', note: '北斗第三真人祿存星君 (狗)' },
  '卯': { star: '文曲星', roleType: 'admin', note: '北斗第四玄冥文曲星君 (兔)' },
  '酉': { star: '文曲星', roleType: 'admin', note: '北斗第四玄冥文曲星君 (雞)' },
  '辰': { star: '廉貞星', roleType: 'judge', note: '北斗第五丹元廉貞星君 (龍)' },
  '申': { star: '廉貞星', roleType: 'judge', note: '北斗第五丹元廉貞星君 (猴)' },
  '巳': { star: '武曲星', roleType: 'warrior', note: '北斗第六北極武曲星君 (蛇)' },
  '未': { star: '武曲星', roleType: 'warrior', note: '北斗第六北極武曲星君 (羊)' },
  '午': { star: '破軍星', roleType: 'warrior', note: '北斗第七天關破軍星君 (馬)' }
};
