// 60 甲子 → 治 / 壇 / 靖 / 官職 / 稱號
export const JIAZI_ZHI_MAPPING = [
  { key: "甲子", name: "天師治", tan: "太一統真壇", jing: "玄元洞靖", official: "都功", title: "洞玄" },
  { key: "乙丑", name: "上清治", tan: "玉華清靈壇", jing: "靈寶正靖", official: "盟威", title: "正真" },
  { key: "丙寅", name: "南陽治", tan: "赤明感應壇", jing: "陽和靖", official: "五雷", title: "感應" },
  { key: "丁卯", name: "葛貴治", tan: "三界集神壇", jing: "洞真自然靖", official: "左都領", title: "暢玄" },
  { key: "戊辰", name: "清虛治", tan: "中央統化壇", jing: "黃中靖", official: "都功", title: "中和" },
  { key: "己巳", name: "真靈治", tan: "紫微伏魔壇", jing: "陽靈靖", official: "盟威", title: "伏魔" },
  { key: "庚午", name: "朱陵治", tan: "南極火德壇", jing: "炎光靖", official: "五雷", title: "火正" },
  { key: "辛未", name: "玄元治", tan: "太上清微壇", jing: "靜應靖", official: "都功", title: "清微" },
  { key: "壬申", name: "北極治", tan: "玄冥御神壇", jing: "元辰靖", official: "盟威", title: "御神" },
  { key: "癸酉", name: "洞陰治", tan: "金真肅靈壇", jing: "肅靈靖", official: "五雷", title: "肅真" },

  { key: "甲戌", name: "玄壇治", tan: "真武鎮邪壇", jing: "北元靖", official: "都功", title: "鎮邪" },
  { key: "乙亥", name: "北平治", tan: "玉堂贊化壇", jing: "降真集靈靖", official: "右都領", title: "降真" },
  { key: "丙子", name: "天關治", tan: "太極啟運壇", jing: "開元靖", official: "盟威", title: "啟運" },
  { key: "丁丑", name: "靈寶治", tan: "三清應化壇", jing: "玄感靖", official: "五雷", title: "應化" },
  { key: "戊寅", name: "洞陽治", tan: "東華布化壇", jing: "青元靖", official: "都功", title: "布化" },
  { key: "己卯", name: "真一治", tan: "太一守真壇", jing: "守一靖", official: "盟威", title: "守真" },
  { key: "庚辰", name: "金華治", tan: "白帝斬邪壇", jing: "金光靖", official: "五雷", title: "斬邪" },
  { key: "辛巳", name: "赤符治", tan: "離火符命壇", jing: "火符靖", official: "都功", title: "符命" },
  { key: "壬午", name: "玄水治", tan: "北冥御水壇", jing: "御水靖", official: "盟威", title: "御水" },
  { key: "癸未", name: "坤元治", tan: "地祇安鎮壇", jing: "安鎮靖", official: "五雷", title: "安鎮" },

  { key: "甲申", name: "神霄治", tan: "雷霆號令壇", jing: "神霄靖", official: "都功", title: "號令" },
  { key: "乙酉", name: "清淨治", tan: "太上清淨壇", jing: "清淨靖", official: "盟威", title: "清淨" },
  { key: "丙戌", name: "赤陽治", tan: "陽明破邪壇", jing: "破邪靖", official: "五雷", title: "破邪" },
  { key: "丁亥", name: "洞冥治", tan: "玄冥召靈壇", jing: "召靈靖", official: "都功", title: "召靈" },
  { key: "戊子", name: "中央治", tan: "中極統御壇", jing: "中極靖", official: "盟威", title: "統御" },
  { key: "己丑", name: "厚德治", tan: "坤德承化壇", jing: "承化靖", official: "五雷", title: "承化" },
  { key: "庚寅", name: "白虎治", tan: "金剛伏魔壇", jing: "伏魔靖", official: "都功", title: "金剛" },
  { key: "辛卯", name: "玉符治", tan: "靈符應感壇", jing: "應感靖", official: "盟威", title: "應感" },
  { key: "壬辰", name: "真水治", tan: "玄水濟世壇", jing: "濟世靖", official: "五雷", title: "濟世" },
  { key: "癸巳", name: "幽冥治", tan: "冥府解厄壇", jing: "解厄靖", official: "都功", title: "解厄" },

  { key: "甲午", name: "炎天治", tan: "南明火德壇", jing: "炎德靖", official: "盟威", title: "炎德" },
  { key: "乙未", name: "福地治", tan: "地祇賜福壇", jing: "賜福靖", official: "五雷", title: "賜福" },
  { key: "丙申", name: "雷門治", tan: "九天雷令壇", jing: "雷令靖", official: "都功", title: "雷令" },
  { key: "丁酉", name: "玉清治", tan: "上清玉籙壇", jing: "玉籙靖", official: "盟威", title: "玉籙" },
  { key: "戊戌", name: "厚載治", tan: "中嶽鎮守壇", jing: "鎮守靖", official: "五雷", title: "鎮守" },
  { key: "己亥", name: "玄真治", tan: "太陰攝靈壇", jing: "攝靈靖", official: "都功", title: "攝靈" },
  { key: "庚子", name: "金闕治", tan: "白帝正刑壇", jing: "正刑靖", official: "盟威", title: "正刑" },
  { key: "辛丑", name: "清剛治", tan: "金剛護法壇", jing: "護法靖", official: "五雷", title: "護法" },
  { key: "壬寅", name: "玄武治", tan: "北極鎮魔壇", jing: "鎮魔靖", official: "都功", title: "鎮魔" },
  { key: "癸卯", name: "太玄治", tan: "玄天應化壇", jing: "應化靖", official: "盟威", title: "太玄" },

  { key: "甲辰", name: "天罡治", tan: "三十六天罡壇", jing: "天罡靖", official: "五雷", title: "天罡" },
  { key: "乙巳", name: "靈火治", tan: "離火煉真壇", jing: "煉真靖", official: "都功", title: "煉真" },
  { key: "丙午", name: "赤霄治", tan: "赤霄雷火壇", jing: "赤霄靖", official: "盟威", title: "赤霄" },
  { key: "丁未", name: "真土治", tan: "坤元養正壇", jing: "養正靖", official: "五雷", title: "養正" },
  { key: "戊申", name: "神虎治", tan: "金虎威令壇", jing: "威令靖", official: "都功", title: "威令" },
  { key: "己酉", name: "玄符治", tan: "太玄符命壇", jing: "符命靖", official: "盟威", title: "符命" },
  { key: "庚戌", name: "白陽治", tan: "金陽破穢壇", jing: "破穢靖", official: "五雷", title: "破穢" },
  { key: "辛亥", name: "清冥治", tan: "玄冥安魂壇", jing: "安魂靖", official: "都功", title: "安魂" },
  { key: "壬子", name: "玄關治", tan: "北玄開關壇", jing: "開關靖", official: "盟威", title: "開關" },
  { key: "癸丑", name: "地載治", tan: "地德厚生壇", jing: "厚生靖", official: "五雷", title: "厚生" },
];

// 12 生肖 → 職務特質
export const ZODIAC_MAPPING = {
  子: { animal: "鼠", trait: "文" },
  丑: { animal: "牛", trait: "武" },
  寅: { animal: "虎", trait: "武" },
  卯: { animal: "兔", trait: "文" },
  辰: { animal: "龍", trait: "判" },
  巳: { animal: "蛇", trait: "判" },
  午: { animal: "馬", trait: "武" },
  未: { animal: "羊", trait: "文" },
  申: { animal: "猴", trait: "判" },
  酉: { animal: "雞", trait: "文" },
  戌: { animal: "狗", trait: "武" },
  亥: { animal: "豬", trait: "判" },
};
